### ISSUE TITLE
Current time marker still rendered on ThresholdGraph when displaying next day's data (after 8 pm)

### ISSUE THREAD

**Issue by neha-vard** [openclimatefix/pv-sites-mobile#165]
**Describe the bug**
The current time marker is still rendered on ThresholdGraph when displaying next day's data (after 8 pm)

**To Reproduce**
Look at ThresholdGraph in dashboard after 8 pm.

**Expected behavior**
Don't render the current time marker when it is past 8 pm.

**Additional context**
Proposed fix: inside the renderCurrentTimeMarker function, return null if it is past 8 pm. Can use same logic as getGraphStartDate and getGraphEndDate to determine if it is past 8 pm.

**Comment by AndrewLester** [comment]
Maybe we should also add some text above the graph to note which day the graph is for (Today, Tomorrow)?

Also, this issue will tie into #160. Check if a fix has already been merged for that issue.
