### ISSUE TITLE
Threshold graph improvements

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#173]
This is a meta issue that involves 3 other issues. We need to improve the threshold graph to make it more interactive and pertinent to the user. Clicking these check boxes _might_ close the corresponding issue (I forget), so be careful.

- [x] #160 
- [x] #165 
- [x] #174

**Comment by ericcccsliu** [comment]
note—all three of these issues should be addressed with just one PR

**Comment by ashayp22** [comment]
We are addressing each of the three issues in separate PRs, so this mega-issue is no longer needed.
