### ISSUE TITLE
Mapbox Input does not work in FireFox

### ISSUE THREAD

**Issue by jackypark9852** [openclimatefix/pv-sites-mobile#191]
**Describe the bug**
if you open the `/site-details` page, the mapbox input component shows a black screen and does not work. 

**To Reproduce**

1. Open `/site-details` in FireFox

**Expected behavior**
Mapbox component should be loaded and functional 

**Additional context**
![image](https://user-images.githubusercontent.com/81858354/229678950-c9aceb73-dabb-4f05-990c-39c018e6539b.png)

**Comment by ashayp22** [comment]
Retested on @jackypark9852's Firefox browser, and the bug was no longer there. Also tested on my Firebox browser and there was no bug.
