### ISSUE TITLE
Threshold graph current time dot doesn't display sometimes

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#195]
**Describe the bug**

Threshold graph current time dot doesn't display sometimes, when it should. It should display when the graph is showing the current day's forecast. One potential reason it's not displaying is that the graph's animation also doesn't appear, implying that the graph re-rendered before the animation could complete, which also tends to break the dot.

**To Reproduce**
Go here: https://pv-sites-mobile-rceroksa2-hack4impact1.vercel.app/dashboard

Note it doesn't display

**Expected behavior**

The threshold graph yellow dot shows up.

**Comment by ericcccsliu** [comment]
fixed by one of Andrew's PRs
