### ISSUE TITLE
Next button on location input overlapping

### ISSUE THREAD

**Issue by kalynwatt** [openclimatefix/pv-sites-mobile#232]
**Describe the bug**
Next button touches map

<img width="978" alt="Screenshot 2023-04-22 at 3 40 02 PM" src="https://user-images.githubusercontent.com/92841900/233805711-9075a8b9-5c75-4c5b-92b1-8c786a64782d.png">

**Expected behavior**
Shouldn't touch map

**Comment by ashayp22** [comment]
Should be resolved in #247
