### ISSUE TITLE
Dashboard and More Info overlap logo

### ISSUE THREAD

**Issue by anyaparekh** [openclimatefix/pv-sites-mobile#233]
**Describe the bug**
The Dashboard and More Info text headings cover the nowcasting logo in mobile view
![image](https://user-images.githubusercontent.com/49364484/233806417-741e9b0b-ae90-4666-a420-4057adebade6.png)

**To Reproduce**

1. Go to /dashboard, /more-info, or /sites
2. Go to mobile view
3. See error

**Expected behavior**
A mobile responsive view, maybe a dropdown or something? Just like how we changed the sidebar in desktop view to a footer in mobile view

**Additional context**
N/A

**Comment by ericcccsliu** [comment]
oh wow, nice catch, tysm!!
