### ISSUE TITLE
Suggestions popping up on every new reverse geocoding result on Vivaldi browser

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#237]
**Describe the bug**

https://user-images.githubusercontent.com/62641231/233855537-f4890642-4778-438f-a8e8-e63699b14cab.mov

**To Reproduce**

1. install vivaldi
2. use site on vivaldi (pref. mobile)
3. zoom in on map
4. move map so reverse geocoding populates search bar
5. see aberrant focus 

**Expected behavior**
Map should move and search bar should populate with new position without search results displaying. 
**Additional context**
Occurred during user testing on user device—Android phone with Vivaldi browser. Might be hard to replicate in other conditions.

**Comment by AndrewLester** [comment]
I was looking into this the other day, and I think the reason is just calling `query` on the geocode instance subsequently calls `focus` on the input element. Seems like Vivaldi automatically opens the keyboard when an input is focused.

**Comment by ericcccsliu** [comment]
> I was looking into this the other day, and I think the reason is just calling `query` on the geocode instance subsequently calls `focus` on the input element. Seems like Vivaldi automatically opens the keyboard when an input is focused.

possible fix: copy and change the code for geocoding queries.

**Comment by AndrewLester** [comment]
Fixed by #219
