### ISSUE TITLE
Have dashboard page remember the last dashboard you were on

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#256]
## Description
Right now, the dashboard page does not go back to the previous dashboard you selected. If you click on a site through the sites sidebar (problem manifests on desktop especially) and click back to more info or something, and then return to dashboard, the aggregate dashboard shows. 

This might be a place for context, or even an issue for local storage (dashboard selection would persist under reload). @AndrewLester @ashayp22 what do y'all think?

**Comment by ashayp22** [comment]
For this specific use case, one idea is saving the site uuid in the More Info URL as `'more-info/[site_uuid]'` or something similar. Then, in the `<NavBar/>` component, we can extract the site uuid and append it to href related to the `<NavbarLink/>` for the dashboard page. 

We can use [next/router](https://nextjs.org/docs/api-reference/next/router#userouter) for this.

If we extend this idea to more pages, then useContext may work, but I encourage starting off simple.
