### ISSUE TITLE
Move "show nav" checks from Layout to individual pages

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#288]
We currently check whether or not to show the navigation UI here, in the Layout:
https://github.com/openclimatefix/pv-sites-mobile/blob/7c5631672e77673e60073d76b6718d251ac1896d/lib/components/Layout.tsx#L12-L16

For context, the navigation UI is hidden on these screens to promote the form's flow, rather than escaping to the rest of the app.

The way we do that is by checking if the current URL is one of the URLs for pages we want to show the nav on. This solution is a bit hacky, mostly since we now have to remember to change these strings if we change URL path names.

An alternative solution is to determine this "show nav", or "hide nav" (which we'll go with since it's fewer pages), in the page tsx files directly. The way this can be done is by attaching a function to each page's page component which returns true if the nav should be hidden, and is assumed to be false if the function doesn't exist. Here's a small example that actually renders an entire layout for each individual page, but we can just pass this variable into the `Layout` component (inside `_app.tsx`) to show/hide the nav.

https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#per-page-layouts

**Comment by ericcccsliu** [comment]
why does this look automated does github do this automatically am i missing out

**Comment by AndrewLester** [comment]
Yeah I just clicked "create new issue from comment or something"
