### ISSUE TITLE
Mock API route for handling site metadata

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#29]
## Description
While the API is being completed, we should create a mock POST route where we can submit our location + form inputs. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] create a mock POST route 
- [ ] ensure the received data has the required [fields](https://github.com/openclimatefix/pv-site-api/blob/30ea5a30728d1be1183e4a539ea120e3706ea164/src/pydantic_models.py#L21-L43) 

## Useful links

- [pydantic models (fields)](https://github.com/openclimatefix/pv-site-api/blob/30ea5a30728d1be1183e4a539ea120e3706ea164/src/pydantic_models.py#L21-L43)

**Comment by AndrewLester** [comment]
Closed in #39
