### ISSUE TITLE
Overlay behind search bar

### ISSUE THREAD

**Issue by anyaparekh** [openclimatefix/pv-sites-mobile#309]
**Describe the bug**
The location search bar in `site-details` endpoint has a black edges

**To Reproduce**

1. Go to `site-details`
2. See error

**Expected behavior**
No black overlay 

**Additional context**
![image](https://github.com/openclimatefix/pv-sites-mobile/assets/49364484/0f713d0f-475b-4983-9a5e-52dff38e1af9)

**Comment by ericcccsliu** [comment]
I think this needs to be fixed through our `globals.css` file. 

<img width="451" alt="image" src="https://github.com/openclimatefix/pv-sites-mobile/assets/62641231/c52b9f3d-486d-451a-9028-b460d5046c31">

this property might be the one that's causing it but idk
