### ISSUE TITLE
Disable OCF Vercel Deployment Temporarily

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#92]
**Describe the bug**
When opening a PR, Vercel seems to choose at random either our deployment or the OCF one to display prominently at the top of the PR. This is confusing for us since we can sometimes view the deployment logs by clicking the top link, and sometimes not (in the case of the OCF deployment). Since our deployment is the only one with correct environment variables and settings at the moment, we were wondering if you could disable the OCF one for this repository temporarily.

@dantravers @braddf

**Comment by ericcccsliu** [comment]
Resolved
